# Generated by Django 3.0.2 on 2020-01-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktops',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100),
        ),
    ]
