# Generated by Django 3.0.2 on 2020-02-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0003_auto_20200130_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='consoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('shipping', models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='desktops',
            name='shipping',
            field=models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='shipping',
            field=models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='shipping',
            field=models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='shipping',
            field=models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100),
        ),
    ]
