# Generated by Django 3.0.2 on 2020-02-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0004_auto_20200211_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoles',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='desktops',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='headphones',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='laptops',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
