# Generated by Django 3.0.7 on 2020-06-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0005_auto_20200211_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consoles',
            name='date',
        ),
        migrations.RemoveField(
            model_name='desktops',
            name='date',
        ),
        migrations.RemoveField(
            model_name='headphones',
            name='date',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='date',
        ),
        migrations.RemoveField(
            model_name='smartphones',
            name='date',
        ),
        migrations.AlterField(
            model_name='consoles',
            name='issues',
            field=models.CharField(default='No issues', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='shipping',
            field=models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consoles',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='issues',
            field=models.CharField(default='No issues', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='shipping',
            field=models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='desktops',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='issues',
            field=models.CharField(default='No issues', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='shipping',
            field=models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='issues',
            field=models.CharField(default='No issues', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='shipping',
            field=models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='issues',
            field=models.CharField(default='No issues', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='shipping',
            field=models.CharField(choices=[('SHIPPABLE', 'item can be shipped'), ('NON-SHIPPABLE', 'item cannot be shipped'), ('SPECIAL-SHIPPING', 'item will be shipped later')], default='SHIPPABLE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Items to be PURCHASED'), ('SOLD', 'Item SOLD'), ('RESTOCKING', 'Items to be RESTOCKED')], default='SOLD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
